FROM python:3.7-alpine
COPY requirements.txt /
RUN apk add --no-cache --virtual .build-deps gcc musl-dev && \
    pip install -r /requirements.txt
COPY defi_in_a_box/ /app
WORKDIR /app
CMD ["python", "defi_in_a_box/main.py"]
